from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class SourceDefinition:
    slug: str
    name: str
    url: str
    category: str
    kind: str = "rss_feed"
    priority: int = 50
    enabled: bool = True
    lang: str = "en"
    interest_tags: tuple[str, ...] = ()
    description: str | None = None
    owner_user_id: int | None = None


DEFAULT_SOURCES: list[SourceDefinition] = [
    # ── Python / ecosystem ──────────────────────────────────────────────────
    SourceDefinition(
        "python-insider",
        "Python Insider",
        "https://blog.python.org/feeds/posts/default",
        "python",
        priority=90,
        interest_tags=("python", "product-news"),
    ),
    SourceDefinition(
        "astral-blog",
        "Astral Blog",
        "https://astral.sh/blog/rss.xml",
        "python",
        priority=85,
        interest_tags=("python", "infra"),
    ),
    SourceDefinition(
        "ruff-releases",
        "Ruff releases",
        "https://github.com/astral-sh/ruff/releases.atom",
        "python",
        "github_release_feed",
        85,
        interest_tags=("python", "infra", "model-releases"),
    ),
    SourceDefinition(
        "uv-releases",
        "uv releases",
        "https://github.com/astral-sh/uv/releases.atom",
        "python",
        "github_release_feed",
        85,
        interest_tags=("python", "infra", "model-releases"),
    ),
    SourceDefinition(
        "mypy-releases",
        "mypy releases",
        "https://github.com/python/mypy/releases.atom",
        "python",
        "github_release_feed",
        80,
        interest_tags=("python", "infra", "model-releases"),
    ),
    SourceDefinition(
        "pyright-releases",
        "Pyright releases",
        "https://github.com/microsoft/pyright/releases.atom",
        "python",
        "github_release_feed",
        80,
        interest_tags=("python", "infra", "model-releases"),
    ),
    SourceDefinition(
        "scikit-learn-releases",
        "scikit-learn releases",
        "https://github.com/scikit-learn/scikit-learn/releases.atom",
        "python",
        "github_release_feed",
        75,
        interest_tags=("python", "model-releases"),
    ),
    SourceDefinition(
        "scipy-releases",
        "SciPy releases",
        "https://github.com/scipy/scipy/releases.atom",
        "python",
        "github_release_feed",
        75,
        interest_tags=("python", "model-releases"),
    ),
    SourceDefinition(
        "pytorch-blog",
        "PyTorch Blog",
        "https://pytorch.org/blog/feed.xml",
        "python",
        priority=80,
        interest_tags=("python", "model-releases", "infra"),
    ),
    SourceDefinition(
        "tensorflow-blog",
        "TensorFlow Blog",
        "https://blog.tensorflow.org/feeds/posts/default",
        "python",
        priority=70,
        interest_tags=("python", "model-releases", "infra"),
    ),
    # ── AI / LLM / agents ───────────────────────────────────────────────────
    SourceDefinition(
        "anthropic-news",
        "Anthropic News",
        "https://www.anthropic.com/news",
        "ai-llm",
        "scraped_page",
        90,
        interest_tags=("agents", "model-releases", "evals", "product-news"),
    ),
    SourceDefinition(
        "openai-blog",
        "OpenAI Blog",
        "https://openai.com/news/rss.xml",
        "ai-llm",
        priority=85,
        interest_tags=("agents", "model-releases", "evals", "product-news"),
    ),
    SourceDefinition(
        "deepmind-blog",
        "Google DeepMind Blog",
        "https://deepmind.google/blog/",
        "ai-llm",
        "scraped_page",
        85,
        interest_tags=("agents", "model-releases", "evals", "product-news"),
    ),
    SourceDefinition(
        "google-ai-blog",
        "Google AI Blog",
        "https://blog.google/technology/ai/rss/",
        "ai-llm",
        priority=75,
        interest_tags=("model-releases", "product-news", "cloud"),
    ),
    SourceDefinition(
        "huggingface-blog",
        "Hugging Face Blog",
        "https://huggingface.co/blog/feed.xml",
        "ai-llm",
        priority=80,
        interest_tags=("model-releases", "infra", "evals"),
    ),
    SourceDefinition(
        "augment-code-blog",
        "Augment Code Blog",
        "https://www.augmentcode.com/blog/rss.xml",
        "ai-llm",
        priority=70,
        interest_tags=("agents", "product-news"),
    ),
    SourceDefinition(
        "simon-willison",
        "Simon Willison",
        "https://simonwillison.net/atom/everything/",
        "ai-llm",
        priority=85,
        interest_tags=("agents", "model-releases", "evals", "python"),
    ),
    SourceDefinition(
        "latent-space",
        "Latent Space",
        "https://www.latent.space/feed",
        "ai-llm",
        priority=65,
        interest_tags=("agents", "model-releases", "product-news"),
    ),
    SourceDefinition(
        "import-ai",
        "Import AI",
        "https://importai.substack.com/feed",
        "ai-llm",
        priority=65,
        interest_tags=("evals", "model-releases"),
    ),
    SourceDefinition(
        "infoq-ai-ml",
        "InfoQ AI/ML/Data",
        "https://feed.infoq.com/ai-ml-data-eng",
        "ai-llm",
        priority=60,
        interest_tags=("infra", "cloud", "model-releases"),
    ),
    SourceDefinition(
        "mistral-ai-news",
        "Mistral AI News",
        "https://mistral.ai/news/",
        "ai-llm",
        "scraped_page",
        80,
        interest_tags=("agents", "model-releases", "product-news"),
    ),
    # ── AI research ──────────────────────────────────────────────────────────
    SourceDefinition(
        "arxiv-ai-ml",
        "arXiv AI/ML",
        "https://rss.arxiv.org/rss/cs.AI",
        "ai-research",
        priority=70,
        interest_tags=("evals", "model-releases", "research"),
    ),
    SourceDefinition(
        "langchain-releases",
        "LangChain releases",
        "https://github.com/langchain-ai/langchain/releases.atom",
        "agents",
        "github_release_feed",
        80,
        interest_tags=("agents", "python", "model-releases"),
    ),
    SourceDefinition(
        "langgraph-releases",
        "LangGraph releases",
        "https://github.com/langchain-ai/langgraph/releases.atom",
        "agents",
        "github_release_feed",
        85,
        interest_tags=("agents", "python", "model-releases"),
    ),
    SourceDefinition(
        "langfuse-releases",
        "Langfuse releases",
        "https://github.com/langfuse/langfuse/releases.atom",
        "agents",
        "github_release_feed",
        80,
        interest_tags=("agents", "infra", "model-releases"),
    ),
    # ── Cloud / infra ────────────────────────────────────────────────────────
    SourceDefinition(
        "kubernetes-blog",
        "Kubernetes Blog",
        "https://kubernetes.io/feed.xml",
        "cloud-infra",
        priority=65,
        interest_tags=("cloud", "infra"),
    ),
    SourceDefinition(
        "docker-blog",
        "Docker Blog",
        "https://www.docker.com/blog/feed/",
        "cloud-infra",
        priority=65,
        interest_tags=("cloud", "infra"),
    ),
    SourceDefinition(
        "aws-ml-blog",
        "AWS Machine Learning Blog",
        "https://aws.amazon.com/blogs/machine-learning/feed/",
        "cloud-infra",
        priority=60,
        interest_tags=("cloud", "infra", "model-releases"),
    ),
    # ── Engineering ──────────────────────────────────────────────────────────
    SourceDefinition(
        "pragmatic-engineer",
        "The Pragmatic Engineer",
        "https://newsletter.pragmaticengineer.com/feed",
        "engineering",
        priority=60,
        interest_tags=("product-news", "infra"),
    ),
    SourceDefinition(
        "github-changelog",
        "GitHub Changelog",
        "https://github.blog/changelog/feed/",
        "engineering",
        priority=65,
        interest_tags=("product-news", "infra"),
    ),
    SourceDefinition(
        "github-engineering",
        "GitHub Engineering",
        "https://github.blog/engineering/feed/",
        "engineering",
        priority=55,
        interest_tags=("infra", "cloud"),
    ),
    # ── Trending / repositories ───────────────────────────────────────────────
    SourceDefinition(
        "hacker-news-best",
        "Hacker News Best",
        "https://hnrss.org/best",
        "trending",
        "trending_feed",
        55,
    ),
    SourceDefinition(
        "hacker-news-ai",
        "Hacker News AI",
        "https://hnrss.org/newest?q=AI",
        "trending",
        "trending_feed",
        55,
    ),
    SourceDefinition(
        "github-trending-all",
        "GitHub Trending All",
        "https://mshibanami.github.io/GitHubTrendingRSS/daily/all.xml",
        "repositories",
        "trending_feed",
        60,
    ),
    SourceDefinition(
        "github-trending-python",
        "GitHub Trending Python",
        "https://mshibanami.github.io/GitHubTrendingRSS/daily/python.xml",
        "repositories",
        "trending_feed",
        70,
    ),
    SourceDefinition(
        "github-trending-typescript",
        "GitHub Trending TypeScript",
        "https://mshibanami.github.io/GitHubTrendingRSS/daily/typescript.xml",
        "repositories",
        "trending_feed",
        60,
    ),
    # ── X / Twitter — AI companies & individuals (via Nitter RSS) ──────────────
    # Handles verified June 2026. Nitter instances are community-run; if feeds
    # stop working update _NITTER_INSTANCES in ingest.py.
    #
    # Company accounts
    SourceDefinition(
        "x-anthropicai",
        "Anthropic (@AnthropicAI)",
        "https://x.com/AnthropicAI",
        "ai-social",
        "nitter_feed",
        80,
    ),
    SourceDefinition(
        "x-openai",
        "OpenAI (@OpenAI)",
        "https://x.com/OpenAI",
        "ai-social",
        "nitter_feed",
        80,
    ),
    SourceDefinition(
        "x-googledeepmind",
        "Google DeepMind (@GoogleDeepMind)",
        "https://x.com/GoogleDeepMind",
        "ai-social",
        "nitter_feed",
        80,
    ),
    SourceDefinition(
        "x-aiatmeta",
        "Meta AI (@AIatMeta)",
        "https://x.com/AIatMeta",
        "ai-social",
        "nitter_feed",
        75,
    ),
    SourceDefinition(
        "x-mistralai",
        "Mistral AI (@MistralAI)",
        "https://x.com/MistralAI",
        "ai-social",
        "nitter_feed",
        75,
    ),
    SourceDefinition(
        "x-huggingface",
        "Hugging Face (@huggingface)",
        "https://x.com/huggingface",
        "ai-social",
        "nitter_feed",
        75,
    ),
    SourceDefinition(
        "x-xai",
        "xAI (@xai)",
        "https://x.com/xai",
        "ai-social",
        "nitter_feed",
        75,
    ),
    # Individuals — lab founders & research leaders
    SourceDefinition(
        "x-darioamodei",
        "Dario Amodei (@DarioAmodei)",
        "https://x.com/DarioAmodei",
        "ai-social",
        "nitter_feed",
        85,
    ),
    SourceDefinition(
        "x-jackclarksf",
        "Jack Clark (@jackclarksf)",
        "https://x.com/jackclarksf",
        "ai-social",
        "nitter_feed",
        70,
    ),
    SourceDefinition(
        "x-sama",
        "Sam Altman (@sama)",
        "https://x.com/sama",
        "ai-social",
        "nitter_feed",
        85,
    ),
    SourceDefinition(
        "x-gdb",
        "Greg Brockman (@gdb)",
        "https://x.com/gdb",
        "ai-social",
        "nitter_feed",
        70,
    ),
    SourceDefinition(
        "x-demishassabis",
        "Demis Hassabis (@demishassabis)",
        "https://x.com/demishassabis",
        "ai-social",
        "nitter_feed",
        85,
    ),
    SourceDefinition(
        "x-ylecun",
        "Yann LeCun (@ylecun)",
        "https://x.com/ylecun",
        "ai-social",
        "nitter_feed",
        80,
    ),
    SourceDefinition(
        "x-arthurmensch",
        "Arthur Mensch (@arthurmensch)",
        "https://x.com/arthurmensch",
        "ai-social",
        "nitter_feed",
        75,
    ),
    SourceDefinition(
        "x-karpathy",
        "Andrej Karpathy (@karpathy)",
        "https://x.com/karpathy",
        "ai-social",
        "nitter_feed",
        85,
    ),
    SourceDefinition(
        "x-clementdelangue",
        "Clement Delangue (@ClementDelangue)",
        "https://x.com/ClementDelangue",
        "ai-social",
        "nitter_feed",
        75,
    ),
    SourceDefinition(
        "x-theo",
        "Theo (@theo)",
        "https://x.com/theo",
        "ai-social",
        "nitter_feed",
        65,
    ),
    # ── Reddit feeds ──────────────────────────────────────────────────────────────
    SourceDefinition(
        "reddit-python",
        "Reddit r/Python",
        "https://www.reddit.com/r/python/",
        "python",
        "reddit_feed",
        80,
        interest_tags=("python", "programming"),
    ),
    SourceDefinition(
        "reddit-machinelearning",
        "Reddit r/MachineLearning",
        "https://www.reddit.com/r/MachineLearning/",
        "ai-llm",
        "reddit_feed",
        75,
        interest_tags=("ai", "ml", "research"),
    ),
    SourceDefinition(
        "reddit-programming",
        "Reddit r/Programming",
        "https://www.reddit.com/r/programming/",
        "python",
        "reddit_feed",
        70,
        interest_tags=("programming", "software-development"),
    ),
    # ── Lobsters feeds ───────────────────────────────────────────────────────────
    SourceDefinition(
        "lobsters",
        "Lobsters",
        "https://lobste.rs/rss",
        "tech",
        "lobsters_feed",
        60,
        interest_tags=("programming", "tech", "startups"),
    ),
    SourceDefinition(
        "lobsters-web",
        "Lobsters Web",
        "https://lobste.rs/t/web.rss",
        "web",
        "lobsters_feed",
        55,
        interest_tags=("web", "frontend", "css"),
    ),
    SourceDefinition(
        "lobsters-ruby",
        "Lobsters Ruby",
        "https://lobste.rs/t/ruby.rss",
        "ruby",
        "lobsters_feed",
        55,
        interest_tags=("ruby", "rails", "backend"),
    ),
    # ── Mastodon feeds ───────────────────────────────────────────────────────────
    SourceDefinition(
        "mastodon-tech",
        "Mastodon Technology",
        "https://mastodon.social/tags/technology.rss",
        "tech",
        "mastodon_feed",
        60,
        interest_tags=("tech", "gadgets", "innovation"),
    ),
    SourceDefinition(
        "mastodon-webdev",
        "Mastodon WebDev",
        "https://mastodon.social/tags/webdev.rss",
        "web",
        "mastodon_feed",
        55,
        interest_tags=("web", "development", "javascript"),
    ),
]
